import React, { useState } from 'react';
import { Shield, DollarSign, Percent, Plus, Trash2, FileText, Check } from 'lucide-react';
import type { TdkState, TradingRule } from '../types';

interface L1MemoryEditorProps {
  state: TdkState;
  onChange: (updates: Partial<TdkState>) => void;
}

export const L1MemoryEditor: React.FC<L1MemoryEditorProps> = ({ state, onChange }) => {
  const [newRuleText, setNewRuleText] = useState('');
  const [newRuleCategory, setNewRuleCategory] = useState<TradingRule['category']>('entry');
  const [activePreviewTab, setActivePreviewTab] = useState<'CLAUDE.md' | 'Risk.md'>('CLAUDE.md');

  // Local handler to update numeric fields safely
  const handleNumChange = (field: keyof TdkState, val: string) => {
    const num = parseFloat(val);
    if (!isNaN(num)) {
      onChange({ [field]: num });
    } else if (val === '') {
      onChange({ [field]: 0 });
    }
  };

  // Rule management handlers
  const handleAddRule = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newRuleText.trim()) return;

    const newRule: TradingRule = {
      id: Math.random().toString(36).substr(2, 9),
      category: newRuleCategory,
      ruleText: newRuleText.trim(),
      enabled: true,
    };

    onChange({
      tradingRules: [...state.tradingRules, newRule],
    });
    setNewRuleText('');
  };

  const handleToggleRule = (id: string) => {
    onChange({
      tradingRules: state.tradingRules.map((rule) =>
        rule.id === id ? { ...rule, enabled: !rule.enabled } : rule
      ),
    });
  };

  const handleDeleteRule = (id: string) => {
    onChange({
      tradingRules: state.tradingRules.filter((rule) => rule.id !== id),
    });
  };

  // Calculations
  const maxRiskPerTradeDollars = (state.accountCapital * state.riskPerTradePercent) / 100;
  const maxDailyDrawdownDollars = (state.accountCapital * state.maxDailyDrawdownPercent) / 100;

  // Markdown Generators
  const generateClaudeMd = () => {
    const activeRules = state.tradingRules.filter((r) => r.enabled);
    const entryRules = activeRules.filter((r) => r.category === 'entry');
    const confRules = activeRules.filter((r) => r.category === 'confirmation');
    const sessionRules = activeRules.filter((r) => r.category === 'session');

    return `# CLAUDE.md - Trading System Context

## System Environment
- **Capital**: $${state.accountCapital.toLocaleString()}
- **Platform**: Trading Dev Kit (TDK) v1.0
- **Operational Mode**: Autonomous-Assisted Execution

## Core Operational Rules

### 1. Market Entry Guidelines
${entryRules.map((r) => `- [ ] ${r.ruleText}`).join('\n') || '- No entry rules configured.'}

### 2. Execution Confirmation
${confRules.map((r) => `- [ ] ${r.ruleText}`).join('\n') || '- No confirmation rules configured.'}

### 3. Session Boundaries
${sessionRules.map((r) => `- [ ] ${r.ruleText}`).join('\n') || '- No session rules configured.'}

---
*Generated by Trading Dev Kit Memory Editor on ${new Date().toLocaleDateString()}*`;
  };

  const generateRiskMd = () => {
    const activeRules = state.tradingRules.filter((r) => r.enabled);
    const riskRules = activeRules.filter((r) => r.category === 'risk');

    return `# Risk.md - System Guardrails

## Account Risk Metrics
- **Total Portfolio Equity**: $${state.accountCapital.toLocaleString()}
- **Risk Per Trade Limit**: ${state.riskPerTradePercent}% ($${maxRiskPerTradeDollars.toLocaleString()})
- **Daily Drawdown Limit**: ${state.maxDailyDrawdownPercent}% ($${maxDailyDrawdownDollars.toLocaleString()})

## Active Risk Guardrails
${riskRules.map((r) => `- [!] ${r.ruleText}`).join('\n') || '- No explicit risk rules configured.'}

## Position Sizing Formula
\`\`\`
Size = Risk_Amount_USD / (Entry_Price - Stop_Loss_Price)
\`\`\`
*Ensure Size does not violate exchange margin ceilings.*

---
*Generated by Trading Dev Kit Memory Editor on ${new Date().toLocaleDateString()}*`;
  };

  return (
    <div className="fade-in">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <div>
          <h2 style={{ fontSize: '1.8rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '10px' }}>
            <Shield className="text-emerald" style={{ color: 'var(--accent-emerald)' }} />
            L1 Memory Editor
          </h2>
          <p style={{ color: 'var(--text-secondary)', marginTop: '4px' }}>
            Configure account guardrails and generate system memory files (`CLAUDE.md` / `Risk.md`).
          </p>
        </div>
        <div className="status-indicator status-active">
          <Check size={14} /> Active Guardrails Loaded
        </div>
      </div>

      {/* Grid of inputs & rule editor */}
      <div className="grid-2" style={{ marginBottom: '24px' }}>
        {/* Risk Profile Card */}
        <div className="glass-panel" style={{ padding: '20px' }}>
          <h3 style={{ fontSize: '1.1rem', marginBottom: '16px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px' }}>
            Risk Profile & Metrics
          </h3>
          
          <div className="form-group">
            <label className="form-label">Account Capital (USD)</label>
            <div style={{ position: 'relative' }}>
              <DollarSign size={16} style={{ position: 'absolute', left: '12px', top: '13px', color: 'var(--text-muted)' }} />
              <input
                type="number"
                className="form-control"
                style={{ paddingLeft: '32px' }}
                value={state.accountCapital || ''}
                onChange={(e) => handleNumChange('accountCapital', e.target.value)}
              />
            </div>
          </div>

          <div className="grid-2">
            <div className="form-group">
              <label className="form-label">Risk Per Trade (%)</label>
              <div style={{ position: 'relative' }}>
                <Percent size={16} style={{ position: 'absolute', left: '12px', top: '13px', color: 'var(--text-muted)' }} />
                <input
                  type="number"
                  step="0.1"
                  className="form-control"
                  style={{ paddingLeft: '32px' }}
                  value={state.riskPerTradePercent || ''}
                  onChange={(e) => handleNumChange('riskPerTradePercent', e.target.value)}
                />
              </div>
            </div>

            <div className="form-group">
              <label className="form-label">Max Daily Drawdown (%)</label>
              <div style={{ position: 'relative' }}>
                <Percent size={16} style={{ position: 'absolute', left: '12px', top: '13px', color: 'var(--text-muted)' }} />
                <input
                  type="number"
                  step="0.5"
                  className="form-control"
                  style={{ paddingLeft: '32px' }}
                  value={state.maxDailyDrawdownPercent || ''}
                  onChange={(e) => handleNumChange('maxDailyDrawdownPercent', e.target.value)}
                />
              </div>
            </div>
          </div>

          {/* Real-time Math Summary */}
          <div style={{ marginTop: '20px', padding: '16px', background: 'rgba(255,255,255,0.02)', borderRadius: '8px', border: '1px dashed var(--border-color)' }}>
            <h4 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: '12px' }}>Calculated Safety Ceilings</h4>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Max Risk per Trade ($):</span>
              <span style={{ fontWeight: 600, color: 'var(--accent-blue)' }}>${maxRiskPerTradeDollars.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between' }}>
              <span style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Max Daily Stop ($):</span>
              <span style={{ fontWeight: 600, color: 'var(--accent-rose)' }}>${maxDailyDrawdownDollars.toLocaleString(undefined, { minimumFractionDigits: 2 })}</span>
            </div>
          </div>
        </div>

        {/* Rule Builder Panel */}
        <div className="glass-panel" style={{ padding: '20px', display: 'flex', flexDirection: 'column' }}>
          <h3 style={{ fontSize: '1.1rem', marginBottom: '16px', borderBottom: '1px solid var(--border-color)', paddingBottom: '8px' }}>
            System Ruleset Builder
          </h3>

          <form onSubmit={handleAddRule} style={{ display: 'flex', gap: '8px', marginBottom: '16px' }}>
            <select
              className="form-control"
              style={{ width: '130px', flexShrink: 0 }}
              value={newRuleCategory}
              onChange={(e) => setNewRuleCategory(e.target.value as TradingRule['category'])}
            >
              <option value="entry">Entry</option>
              <option value="confirmation">Confirm</option>
              <option value="session">Session</option>
              <option value="risk">Risk</option>
            </select>
            
            <input
              type="text"
              placeholder="Enter new rule guidelines..."
              className="form-control"
              value={newRuleText}
              onChange={(e) => setNewRuleText(e.target.value)}
            />

            <button type="submit" className="btn btn-primary" style={{ padding: '0 16px' }}>
              <Plus size={18} />
            </button>
          </form>

          {/* Scrollable Rules List */}
          <div style={{ flexGrow: 1, overflowY: 'auto', maxHeight: '240px', display: 'flex', flexDirection: 'column', gap: '8px', paddingRight: '4px' }}>
            {state.tradingRules.length === 0 ? (
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', textAlign: 'center', margin: 'auto 0' }}>
                No custom rules defined yet. Add one above.
              </p>
            ) : (
              state.tradingRules.map((rule) => {
                let badgeColor = 'var(--accent-blue)';
                if (rule.category === 'risk') badgeColor = 'var(--accent-rose)';
                if (rule.category === 'session') badgeColor = 'var(--accent-amber)';
                if (rule.category === 'confirmation') badgeColor = 'var(--accent-emerald)';

                return (
                  <div
                    key={rule.id}
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      background: 'rgba(255,255,255,0.02)',
                      border: '1px solid var(--border-color)',
                      padding: '10px 12px',
                      borderRadius: '8px',
                      opacity: rule.enabled ? 1 : 0.5,
                      transition: 'opacity 0.2s'
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexGrow: 1 }}>
                      <input
                        type="checkbox"
                        checked={rule.enabled}
                        onChange={() => handleToggleRule(rule.id)}
                        style={{ cursor: 'pointer', width: '16px', height: '16px' }}
                      />
                      <span
                        style={{
                          fontSize: '0.75rem',
                          fontWeight: 600,
                          textTransform: 'uppercase',
                          color: badgeColor,
                          background: `${badgeColor}12`,
                          padding: '2px 6px',
                          borderRadius: '4px',
                          border: `1px solid ${badgeColor}22`
                        }}
                      >
                        {rule.category}
                      </span>
                      <span style={{ fontSize: '0.9rem', color: rule.enabled ? 'var(--text-primary)' : 'var(--text-muted)' }}>
                        {rule.ruleText}
                      </span>
                    </div>
                    <button
                      onClick={() => handleDeleteRule(rule.id)}
                      style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)', display: 'inline-flex', padding: '4px' }}
                      onMouseEnter={(e) => e.currentTarget.style.color = 'var(--accent-rose)'}
                      onMouseLeave={(e) => e.currentTarget.style.color = 'var(--text-muted)'}
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>

      {/* Markdown Preview Area */}
      <div className="glass-panel" style={{ padding: '20px' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', borderBottom: '1px solid var(--border-color)', paddingBottom: '12px' }}>
          <h3 style={{ fontSize: '1.1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FileText size={18} style={{ color: 'var(--accent-blue)' }} />
            Dynamic System Manifests
          </h3>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              className={`btn ${activePreviewTab === 'CLAUDE.md' ? 'btn-primary' : 'btn-secondary'}`}
              style={{ padding: '6px 12px', fontSize: '0.8rem' }}
              onClick={() => setActivePreviewTab('CLAUDE.md')}
            >
              CLAUDE.md
            </button>
            <button
              className={`btn ${activePreviewTab === 'Risk.md' ? 'btn-primary' : 'btn-secondary'}`}
              style={{ padding: '6px 12px', fontSize: '0.8rem' }}
              onClick={() => setActivePreviewTab('Risk.md')}
            >
              Risk.md
            </button>
          </div>
        </div>

        <pre className="terminal-code" style={{ whiteSpace: 'pre-wrap', maxHeight: '300px' }}>
          {activePreviewTab === 'CLAUDE.md' ? generateClaudeMd() : generateRiskMd()}
        </pre>
      </div>
    </div>
  );
};
